#!/usr/bin/env python
"""
    SSDP Notify
    
    @author: Jean-Lou Dupont
"""
__version__="0.1"
import os, sys, argparse
op=os.path

try:
    import jldssdp #@UnusedImport
except:
    ### must be in dev mode then    
    this_dir=op.dirname(__file__)
    lib_path=op.abspath(op.join(this_dir, ".."))
    sys.path.insert(0, lib_path)
    import jldssdp #@UnusedImport

########################################################################

DESC="SSDP Notify - version %s" % __version__
DEFAULTS={
          }

def main():
    try:
        import jldssdp.do_setup #@UnusedImport
        import logging
        import jldssdp.do_checks #@UnusedImport
        
        import jldssdp.helpers as helpers
        
        eth0 = helpers.get_eth0_ipv4()
        
        parser=argparse.ArgumentParser(description=DESC, fromfile_prefix_chars='@')
        parser.add_argument('-eth0',   dest='eth0',   type=str, help="eth0", default=eth0)
        parser.add_argument('-usn',    dest='usn',    type=str, help="USN", default="590d9c13-0f12-4232-ace7-0b614fcf38b6")
        parser.add_argument('-nt',     dest='nt',     type=str, help="NT", default = "urn:systemical:device:hub:1")
        parser.add_argument('-loc',    dest='loc',    type=str, help="LOCATION", default="http://%(eth0)s/hub")
        parser.add_argument('-delay',  dest='delay',  type=int, help="Loop delay", default=30)
        parser.add_argument('-noloop', dest='noloop', action="store_true", help="Disable loop")
        
        args=parser.parse_args()
        
        from jldssdp.tools_sys import dnorm, info_dump
        from jldssdp.script_notify import run
        
        args=dnorm(vars(args))
        info_dump(args, 20)       
        run(**args)


    except KeyboardInterrupt:
        logging.info("... exiting")
        sys.exit(0)##no probs
        
    except Exception,e:
        logging.error(str(e))
        sys.exit(1)
        

sys.exit(main())
